Program PC_EKKA;

uses
  Forms,
  StartU in 'StartU.pas' {StartF},
  LogoU in 'LogoU.pas' {LogoF},
  DataModuleU in 'DataModuleU.pas' {DM: TDataModule},
  MainU in 'MainU.pas' {MainF},
  UsersU in 'UsersU.pas' {UsersF},
  EnterKolU in 'EnterKolU.pas' {EnterKolF},
  OstatCheckU in 'OstatCheckU.pas' {OstatCheckF},
  Digits in 'Digits.pas',
  PasswU in 'PasswU.pas' {PasswF},
  DialogU in 'DialogU.pas' {DialogF},
  BlockingU in 'BlockingU.pas' {BlockingF},
  DateBackU in 'DateBackU.pas' {DateBackF},
  MoveTovU in 'MoveTovU.pas' {MoveTovF},
  RealizRepU in 'RealizRepU.pas' {RealizRepF},
  CardReadU in 'CardReadU.pas' {CardReadF},
  AECardsU in 'AECardsU.pas' {AECardsF},
  ZXRepU in 'ZXRepU.pas' {ZXRepF},
  Marry301U in '..\Classes\Marry301U.pas',
  ShowEAN13U in 'ShowEAN13U.pas' {ShowEAN13F},
  ViewNaklU in 'ViewNaklU.pas' {ViewNaklF},
  SumZPerU in 'SumZPerU.pas' {SumZPerF},
  SumZU in 'SumZU.pas' {SumZF},
  ShareU in 'ShareU.pas',
  EnterStrU in 'EnterStrU.pas' {EnterStrF},
  OptSumU in 'OptSumU.pas' {OptSumF},
  LoadNaklU in 'LoadNaklU.pas' {LoadNaklF},
  NaklInfoU in 'NaklInfoU.pas' {NaklInfoF},
  ZakazU in 'ZakazU.pas' {ZakazF},
  MoveMoneyU in 'MoveMoneyU.pas' {MoveMoneyF},
  ShowTerminalAlertU in 'ShowTerminalAlertU.pas' {ShowTerminalAlertF},
  ShowCardInfoU in 'ShowCardInfoU.pas' {ShowCardInfoF},
  BankCardU in 'BankCardU.pas' {BankCardF},
  OtkazU in 'OtkazU.pas' {OtkazF},
  NoScanU in 'NoScanU.pas' {NoScanF},
  ShowATCU in 'ShowATCU.pas' {ShowATCF},
  ChekListU in 'ChekListU.pas' {ChekListF},
  BackClientU in 'BackClientU.pas' {BackClientF},
  InitCPU in 'InitCPU.pas' {InitCPF},
  RepKassirSummU in 'RepKassirSummU.pas' {RepKassirSummF},
  RepOstatU in 'RepOstatU.pas' {RepOstatF},
  RepPeriodU in 'RepPeriodU.pas' {RepPeriodF},
  ThPrintChpU in 'ThPrintChpU.pas',
  InfoPKUU in 'InfoPKUU.pas' {InfoPKUF},
  RepIncomU in 'RepIncomU.pas' {RepIncomF},
  TermEKKAU in 'TermEKKAU.pas' {TermEKKAF},
  CutBaseU in 'CutBaseU.pas' {CutBaseF},
  ShowNewInfoU in 'ShowNewInfoU.pas' {ShowNewInfoF},
  EditRegU in 'EditRegU.pas' {EditRegF},
  HistoryU in 'HistoryU.pas' {HistoryF},
  WorkSprU in 'WorkSprU.pas' {WorkSprF},
  ViewLTU in 'ViewLTU.pas' {ViewLTF},
  JTableU in 'JTableU.pas' {JTableF},
  CancelViewU in 'CancelViewU.pas' {CancelViewF},
  TableU in 'TableU.pas' {TableF},
  AETabU in 'AETabU.pas' {AETabF},
  PeresortU in 'PeresortU.pas' {PeresortF},
  CheckBaseU in 'CheckBaseU.pas' {CheckBaseF},
  RepRegU in 'RepRegU.pas' {RepRegF},
  KolProdU in 'KolProdU.pas' {KolProdF},
  SpisU in 'SpisU.pas' {SpisF},
  PrOtkazU in 'PrOtkazU.pas' {PrOtkazF},
  ShowMessU in 'ShowMessU.pas' {ShowMessF},
  Datecs3530TU in '..\Classes\Datecs3530TU.pas',
  EKKAU in '..\Classes\EKKAU.pas',
  SpisArtAddU in 'SpisArtAddU.pas' {SpisArtAddF},
  PrintMarkBoxU in 'PrintMarkBoxU.pas' {PrintMarkBoxF},
  JReocU in 'JReocU.pas' {JReocF},
  AkciiU in 'AkciiU.pas' {AkciiF},
  DialogVozrSpisU in 'DialogVozrSpisU.pas' {DialogVozrSpisF},
  SpisUserU in 'SpisUserU.pas' {SpisUserF},
  ShowJMessU in 'ShowJMessU.pas' {ShowJMessF},
  HistoryMessJU in 'HistoryMessJU.pas' {HistoryMessJF},
  ShowNonRegU in 'ShowNonRegU.pas' {ShowNonRegF},
  PswU in 'PswU.pas' {PswF},
  EnterValueU in 'EnterValueU.pas' {EnterValueF},
  BlankReciptU in 'BlankReciptU.pas' {BlankReciptF},
  PrintObnovU in 'PrintObnovU.pas' {PrintObnovF},
  MoneyCashU in 'MoneyCashU.pas' {MoneyCashF},
  SetPhoneU in 'SetPhoneU.pas' {SetPhoneF},
  ShowTerapU in 'ShowTerapU.pas' {ShowTerapF},
  EnterDateU in 'EnterDateU.pas' {EnterDateF},
  CenaUpakU in 'CenaUpakU.pas' {CenaUpakF},
  Mess1U in 'Mess1U.pas' {Mess1F},
  ScanBoxU in 'ScanBoxU.pas' {ScanBoxF},
  RegPredstU in 'RegPredstU.pas' {RegPredstF},
  SimpleMessU in 'SimpleMessU.pas' {SimpleMessF},
  SentMessU in 'SentMessU.pas' {SentMessF},
  EnterDate1U in 'EnterDate1U.pas' {EnterDate1F},
  SertifIU in 'SertifIU.pas' {SertifIF},
  AddResU in 'AddResU.pas' {AddResF},
  WorkResU in 'WorkResU.pas' {WorkResF},
  ScanMagU in 'ScanMagU.pas' {ScanMagF},
  ShowAkciiU in 'ShowAkciiU.pas' {ShowAkciiF},
  ScanStretchU in 'ScanStretchU.pas' {ScanStretchF},
  ChooseVLU in 'ChooseVLU.pas' {ChooseVLF},
  ShowKolForVozrU in 'ShowKolForVozrU.pas' {ShowKolForVozrF},
  MSXML_TLB in 'MSXML_TLB.pas',
  SendReceiveXML in '..\Classes\SendReceiveXML.pas',
  MBSpisU in 'MBSpisU.pas' {MBSpisF},
  ProvizInfoU in 'ProvizInfoU.pas' {ProvizInfoF},
  SignInfoU in 'SignInfoU.pas' {SignInfoF},
  HotKeyInfoU in 'HotKeyInfoU.pas' {HotKeyInfoF},
  ScanNaklU in 'ScanNaklU.pas' {ScanNaklF},
  EnterKolScanU in 'EnterKolScanU.pas' {EnterKolScanF},
  TabelU in 'TabelU.pas' {TabelF},
  FirstRecU in 'FirstRecU.pas' {FirstRecF},
  CountersU in 'CountersU.pas' {CountersF},
  ShowRecOnlyU in 'ShowRecOnlyU.pas' {ShowRecOnlyF},
  LTMU in 'LTMU.pas' {LTMF},
  FormForVozrU in 'FormForVozrU.pas' {FormForVozrF},
  ReasonNoTovU in 'ReasonNoTovU.pas' {ReasonNoTovF},
  FirstRecomendU in 'FirstRecomendU.pas' {FirstRecomendF},
  ShowBackClInstructU in 'ShowBackClInstructU.pas' {ShowBackClInstructF},
  PrihodMDMU in 'PrihodMDMU.pas' {PrihodMDMF},
  OstatInBSkladU in 'OstatInBSkladU.pas' {OstatInBSkladF},
  ShowTextU in 'ShowTextU.pas' {ShowTextF},
  ClDiagU in 'ClDiagU.pas' {ClDiagF},
  KoefU in 'KoefU.pas' {KoefF},
  EnterNDocU in 'EnterNDocU.pas' {EnterNDocF},
  Pilot1U in 'Pilot1U.pas' {Pilot1F},
  Pilot2U in 'Pilot2U.pas' {Pilot2F},
  Pilot3U in 'Pilot3U.pas' {Pilot3F},
  WorkTimeU in 'WorkTimeU.pas' {WorkTimeF},
  VSostU in 'VSostU.pas' {VSostF},
  ConfirmZpMessU in 'ConfirmZpMessU.pas' {ConfirmZpMessF},
  ChoosePrihU in 'ChoosePrihU.pas' {ChoosePrihF},
  PrihTovU in 'PrihTovU.pas' {PrihTovF},
  SpisTovAllU in 'SpisTovAllU.pas' {SpisTovAllF},
  PilotU in 'PilotU.pas' {PilotF},
  SpisForVozrU in 'SpisForVozrU.pas' {SpisForVozrF},
  ScanVozrU in 'ScanVozrU.pas' {ScanVozrF},
  ChooseVL1U in 'ChooseVL1U.pas' {ChooseVL1F},
  PrVozrU in 'PrVozrU.pas' {PrVozrF},
  ZakazPriceU in 'ZakazPriceU.pas' {ZakazPriceF},
  OpenOffice in 'OpenOffice.pas',
  HodAkciiU in 'HodAkciiU.pas' {HodAkciiF},
  ViewZakazPriceU in 'ViewZakazPriceU.pas' {ViewZakazPriceF},
  ViewVzResU in 'ViewVzResU.pas' {ViewVzResF},
  HozZakazU in 'HozZakazU.pas' {HozZakazF},
  ChMonthU in 'ChMonthU.pas' {ChMonthF},
  CheckLoginU in 'CheckLoginU.pas' {CheckLoginF},
  TovInfoU in 'TovInfoU.pas' {TovInfoF},
  TovGrafikU in 'TovGrafikU.pas' {TovGrafikF},
  NoScanViewU in 'NoScanViewU.pas' {NoScanViewF},
  ShowPictU in 'ShowPictU.pas' {ShowPictF},
  GrafikInfoU in 'GrafikInfoU.pas' {GrafikInfoF},
  EnterKolAdvU in 'EnterKolAdvU.pas' {EnterkolAdvF},
  ShowTekOtpU in 'ShowTekOtpU.pas' {ShowTekOtpF},
  MessThemsU in 'MessThemsU.pas' {MessThemsF},
  SrokMovU in 'SrokMovU.pas' {SrokMovF},
  svButtons in '..\Classes\svButtons.pas',
  ChoosePostavU in 'ChoosePostavU.pas' {ChoosePostavF},
  QOldToNewU in 'QOldToNewU.pas' {QOldToNewF},
  MessBoxU in 'MessBoxU.pas' {MessBoxF},
  SaveScreenU in 'SaveScreenU.pas' {SaveScreenF},
  DocumentsU in 'DocumentsU.pas' {DocumentsF},
  AETabNewU in 'AETabNewU.pas' {AETabNewF},
  ShowSimpTextU in 'ShowSimpTextU.pas' {ShowSimpTextF},
  GrafikU in 'GrafikU.pas' {GrafikF},
  FormHintU in 'FormHintU.pas' {FormHintF},
  EnterKolNewU in 'EnterKolNewU.pas' {EnterKolNewF},
  hSosputstvU in 'hSosputstvU.pas' {hSoputstvF},
  hPokupStatU in 'hPokupStatU.pas' {hPokupStatF},
  ShowZpMessU in 'ShowZpMessU.pas' {ShowZpMessF},
  hKonkurHintU in 'hKonkurHintU.pas' {hKonkurHintF},
  ShowAlarmU in 'ShowAlarmU.pas' {ShowAlarmF},
  ReestrU in 'ReestrU.pas' {ReestrF},
  ShowAnnotNewU in 'ShowAnnotNewU.pas' {ShowAnnotNewF},
  SpisNeedAktU in 'SpisNeedAktU.pas' {SpisNeedAktF},
  WebGeptralU in 'WebGeptralU.pas' {WebGeptralF},
  ArmourInApteksU in 'ArmourInApteksU.pas' {ArmourInApteksF},
  CancelResU in 'CancelResU.pas' {CancelResF},
  ExtImage in 'ExtImage.pas',
  JPaySlipU in 'JPaySlipU.pas' {JPaySlipF},
  JPaySlipU1 in 'JPaySlipU1.pas' {JPaySlipF1},
  JPaySlipU2 in 'JPaySlipU2.pas' {JPaySlipF2},
  RepKassirSumm1U in 'RepKassirSumm1U.pas' {RepKassirSumm1F},
  MotivationSystemU in 'MotivationSystemU.pas' {MotivationSystemF},
  ViewMapU in 'ViewMapU.pas' {ViewMapF},
  WelcomeU in 'WelcomeU.pas' {WelcomeF},
  BackTMCU in 'BackTMCU.pas' {BackTMCF},
  ChoosePayU in 'ChoosePayU.pas' {ChoosePayF},
  BankCard_old_U in 'BankCard_old_U.pas' {BankCard_old_F},
  ShowReciptListU in 'ShowReciptListU.pas' {ShowReciptListF},
  ListMakeFromU in 'ListMakeFromU.pas' {ListMakeFromF},
  ChooseReciptU in 'ChooseReciptU.pas' {ChooseReciptF},
  OtkazInfoU in 'OtkazInfoU.pas' {OtkazInfoF},
  SpisArtCenaU in 'SpisArtCenaU.pas' {SpisArtCenaF},
  LgotListU in 'LgotListU.pas' {LgotListF},
  TimerZU in 'TimerZU.pas' {TimerZF},
  ZPU in 'ZPU.pas' {ZpF},
  AddExtemoroU in 'AddExtemoroU.pas' {AddExtemoroF},
  DiagnosticRepairU in 'DiagnosticRepairU.pas' {DiagnosticRepairF},
  PiggyBankU in 'PiggyBankU.pas' {PiggyBankF},
  VozrPartU in 'VozrPartU.pas' {VozrPartF},
  AkciiStatU in 'AkciiStatU.pas' {AkciiStatF},
  CheckSMSKodU in 'CheckSMSKodU.pas' {CheckSMSKodF},
  PlayRolikU in 'PlayRolikU.pas' {PlayRolikF},
  ChangeMDMCardU in 'ChangeMDMCardU.pas' {ChangeMDMCardF},
  ShowStatPlanAptU in 'ShowStatPlanAptU.pas' {ShowStatPlanAptF},
  PlayerU in 'PlayerU.pas' {PlayerF},
  ReklamaOnU in 'ReklamaOnU.pas' {ReklamaOnF},
  hFarmZamAlertU in 'hFarmZamAlertU.pas' {hFarmZamAlertF},
  hPlanInfoU in 'hPlanInfoU.pas' {hPlanInfoF},
  hPlanAptInfoU in 'hPlanAptInfoU.pas' {hPlanAptInfoF},
  BackSkladInfoU in 'BackSkladInfoU.pas' {BackSkladInfoF},
  PlanForAptekaU in 'PlanForAptekaU.pas' {PlanForAptekaF},
  AddDoctorU in 'AddDoctorU.pas' {AddDoctorF},
  UserListU in 'UserListU.pas' {UserListF},
  AddStrahU in 'AddStrahU.pas' {AddStrahF},
  OtkritkaU in 'OtkritkaU.pas' {OtkritkaF},
  EnterCash in 'EnterCash.pas' {FormEnterCash},
  DailyOperationSelection in 'DailyOperationSelection.pas' {FormDailyOperationSelection},
  ReturnToProviderU in 'ReturnToProviderU.pas' {ReturnToProviderF},
  AddToReturnU in 'AddToReturnU.pas' {AddToReturnF},
  NewReocListU in 'NewReocListU.pas' {NewReocListF},
  PiggyBankRepU in 'PiggyBankRepU.pas' {PiggyBankRepF},
  TotalStatU in 'TotalStatU.pas' {TotalStatF},
  NeedAktU in 'NeedAktU.pas' {NeedAktF},
  ReestrRepU in 'ReestrRepU.pas' {ReestrRepF},
  CalculatePlanU in 'CalculatePlanU.pas' {CalculatePlanF},
  ViolationDiagU in 'ViolationDiagU.pas' {ViolationDiagF},
  ListBackPartU in 'ListBackPartU.pas' {ListBackPartF},
  GetNumCardSMSU in 'GetNumCardSMSU.pas' {GetNumCardSMSF},
  PrintAnnotU in 'PrintAnnotU.pas' {PrintAnnotF},
  ReplConnectionEditU in 'ReplConnectionEditU.pas' {ReplConnectionEditF},
  ReplPhoneAccountU in 'ReplPhoneAccountU.pas' {ReplPhoneAccountF},
  Un_to_chek in 'Un_to_chek.pas' {Fn_to_chek},
  UGarant_remont in 'UGarant_remont.pas' {FGarant_remont},
  Utake_product in 'Utake_product.pas' {FTake_product},
  UDeliveryCashInput in 'UDeliveryCashInput.pas' {DeliveryCashInputF},
  QuarantineU in 'QuarantineU.pas' {QuarantineF},
  BonusStateU in 'BonusStateU.pas' {BonusStateF},
  UTmp_change_employee in 'UTmp_change_employee.pas' {FTmp_change_employee},
  QuarantineEditU in 'QuarantineEditU.pas' {QuarantineEditF},
  ClaimesU in 'ClaimesU.pas' {ClaimesF},
  ViewLessonsU in 'ViewLessonsU.pas' {ViewLessonsF},
  ZakazPodKlientaU in 'ZakazPodKlientaU.pas' {ZakazPodKlientaF},
  ScanPosInfoU in 'ScanPosInfoU.pas' {ScanPosInfoF},
  FarmZamAndSoputstvU in 'FarmZamAndSoputstvU.pas' {FarmZamAndSoputstvF},
  MesHranSrokU in 'MesHranSrokU.pas' {MesHranSrokF},
  StickerForBoxU in 'StickerForBoxU.pas' {StickerForBoxF},
  InsulinU in 'InsulinU.pas' {InsulinF},
  DocumentsExtendedU in 'DocumentsExtendedU.pas' {DocumentsExtendedF},
  InsulinRepU in 'InsulinRepU.pas' {InsulinRepF},
  Uedit_filtr in 'Uedit_filtr.pas' {Fedit_filter},
  PlanMotivationStatU in 'PlanMotivationStatU.pas' {PlanMotivationStatF},
  Uadd_counter in 'Uadd_counter.pas' {Fadd_counter},
  ChangeArticleCount in 'ChangeArticleCount.pas' {fmChangeCount},
  WinHttpRequest in 'WinHttpRequest.pas',
  OptimaDiscount in 'OptimaDiscount.pas';

{$R *.res}

BEGIN
  Application.Initialize;
  Application.Title := 'Pc_ekka';
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TStartF, StartF);
  Application.CreateForm(ThSoputstvF, hSoputstvF);
  Application.CreateForm(ThPokupStatF, hPokupStatF);
  Application.CreateForm(ThKonkurHintF, hKonkurHintF);
  Application.CreateForm(ThFarmZamAlertF, hFarmZamAlertF);
  Application.CreateForm(ThPlanInfoF, hPlanInfoF);
  Application.CreateForm(TSimpleMessF, SimpleMessF);
  Application.CreateForm(TPlayerF, PlayerF);
  Application.CreateForm(ThPlanAptInfoF, hPlanAptInfoF);
  Application.Run;
END.
